### ISSUE TITLE
Getting no Error but where this file download

### ISSUE THREAD

**Issue by Ankitkhatrani** [santoshshinde2012/FileTransfer_Upload#3]
"source":"http://192.168.1.2/ionic_project/video_status/public/video/Bewafa_Pyar_Ki_Kahani.mp4",
"target":"http://192.168.1.2/ionic_project/video_stat/platforms/browser/www/img/Bewafa_Pyar_Ki_Kahani.mp4"

I have used browser platform 
  getting no error but file not found in targeted folder

can you help me to find the file where it's stored?

**Comment by santoshshinde2012** [comment]
this is not having option for browser platform

**Comment by Ankitkhatrani** [comment]
thank you for your replay.
